
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DesfacaFacil.Models
{

using System;
    using System.Collections.Generic;
    
public partial class IMAGEN
{

    public decimal IID { get; set; }

    public Nullable<decimal> AID { get; set; }

    public string NOME { get; set; }

    public string CAMINHO { get; set; }



    public virtual ANUNCIO ANUNCIO { get; set; }

}

}
