//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesfacaFacil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANUNCIO
    {
        public ANUNCIO()
        {
            this.MENSAGENS = new HashSet<MENSAGEN>();
            this.USUARIOS = new HashSet<USUARIO>();
        }
    
        public decimal AID { get; set; }
        public decimal USID { get; set; }
        public decimal CID { get; set; }
        public decimal TIPO { get; set; }
        public decimal STATUS { get; set; }
        public System.DateTime DATACRIACAO { get; set; }
        public System.DateTime DATAEXPIRACAO { get; set; }
        public string DESCRICAO { get; set; }
        public string TITULO { get; set; }
    
        public virtual ICollection<MENSAGEN> MENSAGENS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual ICollection<USUARIO> USUARIOS { get; set; }
    }
}
