//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesfacaFacil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANUNCIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANUNCIO()
        {
            this.MENSAGENS = new HashSet<MENSAGEN>();
            this.CANDIDATOS = new HashSet<CANDIDATO>();
            this.IMAGENS = new HashSet<IMAGEN>();
        }
    
        public decimal AID { get; set; }
        public decimal USID { get; set; }
        public decimal CID { get; set; }
        public decimal TIPO { get; set; }
        public decimal STATUS { get; set; }
        public System.DateTime DATACRIACAO { get; set; }
        public System.DateTime DATAEXPIRACAO { get; set; }
        public string DESCRICAO { get; set; }
        public string TITULO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MENSAGEN> MENSAGENS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CANDIDATO> CANDIDATOS { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IMAGEN> IMAGENS { get; set; }
    }
}
