//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesfacaFacil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA
    {
        public CATEGORIA()
        {
            this.ANUNCIOs = new HashSet<ANUNCIO>();
        }
    
        public decimal CID { get; set; }
        public string NOME { get; set; }
    
        public virtual ICollection<ANUNCIO> ANUNCIOs { get; set; }
    }
}
