//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesfacaFacil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.ANUNCIOs = new HashSet<ANUNCIO>();
            this.ENDERECOes = new HashSet<ENDERECO>();
            this.ANUNCIOs1 = new HashSet<ANUNCIO>();
        }
    
        public decimal USID { get; set; }
        public decimal STATUS { get; set; }
        public string NOME { get; set; }
        public string EMAIL { get; set; }
        public string TELEFONE { get; set; }
        public Nullable<System.DateTime> DATACADASTRO { get; set; }
        public string SENHA { get; set; }
    
        public virtual ICollection<ANUNCIO> ANUNCIOs { get; set; }
        public virtual ICollection<ENDERECO> ENDERECOes { get; set; }
        public virtual ICollection<ANUNCIO> ANUNCIOs1 { get; set; }
    }
}
